version: '3'
services:
  question-service:
    container_name: question-service
    image: rodrigotrentinrossi/question-service
    restart: always
    build: .
    ports:
      - '4001:4001'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodata:
